kind: pipeline
steps:
- name: Unit testing
  image: maven:3-jdk-11
  commands:
  - mvn package
  - mvn test
- name: SonarQube
  image: maven:3-jdk-11
  commands: 
  - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=Blackace1 -Dsonar.host.url=http://48e9-190-148-78-2.ngrok.io
- name: QualityGate
  image: maven:3-jdk-11
  commands:
  - mvn clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=hola -Dsonar.host.url=http://48e9-190-148-78-2.ngrok.io
- name: Production
    image: maven:3-jdk-11
    commands:
      - mvn tomcat7:redeploy
