kind: pipeline
steps:
- name: Unit testing
  image: maven:3-jdk-11
  commands:
  - mvn package
  - mvn test
  
- name: procesosSonarQube
  image: maven:3-jdk-11
  commands: 
  - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=Blackace1 -Dsonar.host.url=http://d1b4-190-148-78-2.ngrok.io
  
- name: tomcatMain
  image: maven:3-jdk-11
  commands:
    - mvn -Dspring.profiles.active=main clean  install
    - mvn -Dspring.profiles.active=main package
    - cd target/
    - mv  ventas-0.0.1-SNAPSHOT.war mainDrone.war
    - curl -v -u admin:adminSecure -T mainDrone.war 'http://4f34-190-148-78-2.ngrok.io/manager/text/deploy?path=/mainDrone&update=true'
  when:
    branch:
      - main
    event:
      include:
      - push
      

- name: Sonarq_email
  image: drillster/drone-email
  settings:
    from: juanestebancdl@gmail.com
    host: smtp.gmail.com
    port: 465
    username:
       from_secret: email
    password: 
      from_secret: contra
    subject: Pipeline Fail
    recipients:
        - caceres181049@unis.edu.gt
        - jflores@unis.edu.gt
  when:
    status:
    - failure

- name: slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack
    channel: general
  when:
    status: [ success, failure ]
