kind: pipeline
steps:
- name: Unit testing
  image: maven:3-jdk-11
  commands:
  - mvn package
  - mvn test
  
- name: SonarQube
  image: maven:3-jdk-11
  commands: 
  - mvn clean verify sonar:sonar -Dsonar.login=admin -Dsonar.password=Blackace1 -Dsonar.host.url=http://93f8-190-148-78-2.ngrok.io
- name: QualityGate
  image: maven:3-jdk-11
  commands:
  - mvn clean verify sonar:sonar sonar-quality-gate:check -Dsonar.login=admin -Dsonar.password=Blackace1 -Dsonar.host.url=http://93f8-190-148-78-2.ngrok.io
  
- name: Sonarq_email
  image: drillster/drone-email
  settings:
    from: juanestebancdl@gmail.com
    host: smtp.gmail.com
    port: 465
    username:
       from_secret: admin
    password: 
      from_secret: Blackace1
    subject: Pipeline QualityGate Fail
    recipients:
        - caceres181049@unis.edu.gt
        - jflores@unis.edu.gt
  when:
    status:
    - failure
