pipeline {
    agent any 
    stages {
        stage('checkout'){
            steps{
                git 'https://github.com/JuanCaceresDL/arquitecturadesistemas.git'
                }
            }
        stage('unit testing') { 
            steps {
                withMaven(maven: 'maven') {
                sh 'mvn test'
                }
            }
        }
        stage('sonarqube') { 
            steps {
                def mvnHome =  tool name: 'maven', type: 'maven'
                    withSonarQubeEnv('sonarqube') {
                        sh "${mvnHome}/bin/mvn verify sonar:sonar -Dsonar.login=admin -Dsonar.password=Blackace1"
                    }
            }
        }
        //stage('Deploy') { 
         //   steps {
                // 
           // }
        //}
    }
}