pipeline {
    agent any 
    tools{
      maven 'maven'
   }
    stages {
        stage('checkout'){
            steps{
                git 'https://github.com/JuanCaceresDL/arquitecturadesistemas.git'
                }
            }
        /*stage('unit testing') { 
            steps {
                withMaven(maven: 'maven') {
                sh 'mvn -f sistemaVentas/pom.xml test'
                }
            }
        }*/   
        stage('proceso de sonarqube'){
                try {
                    steps{
                        withSonarQubeEnv('sonarqube') {
                            sh "mvn -f sistemaVentas/pom.xml sonar:sonar -Dsonar.login=admin -Dsonar.password=Blackace1"
                            }
                        }
                }catch (err) {
                    emailext body: 'algo salió mal', subject: 'error de pipeline', to: 'juanestebancdl@gmail.com'
                    }
        }

        //stage('Deploy') { 
         //   steps {
                // 
           // }
        //}
    }
}